version: '3'

services:
  mysql:
    container_name: mysql_db
    image: mysql:8
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: full-stack-ecommerce
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=root" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_volume: